# Generated by Django 3.2.16 on 2023-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profil',
            field=models.CharField(choices=[('developpeur', 'developpeur'), ('graphiste', 'graphiste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='Images', verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Prestataire', 'Prestataire')], max_length=20),
        ),
    ]
